<?php

namespace App\Test\TestCase;

use Cake\TestSuite\TestCase;

class CommentsApiTest extends TestCase {

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetComments() {
        $commentsTable = $this->getTableLocator()->get('Comments');
        $comment = $commentsTable->newEntity(['username' => 'test','commentable_id' => 1, 'ip' => 'post', 'commentable_type' => 1]);
        $commentsTable->save($comment);
        $comments = $commentsTable->find()->toArray();
        $this->assertEquals(1, count($comments));
    }
}
